# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:envrc:
    desc: Generate direnv config from ".envrc.example".
    cmds:
      - cat .envrc.example | sed -e 's/^# .*//' > .envrc
      - sed -i "" '/^[[:space:]]*$$/d' .envrc
      - sed -i "" '/^$/d' .envrc
      - sed -i "" 's/^/export /' .envrc
    sources:
      - .envrc.example
    generates:
      - .envrc

  dev:setup:
    desc: Setup local environment and install dependencies.
    run: once
    cmds:
      - task: npm:install
      - task: seed

  npm:install:
    desc: Install node dependencies.
    run: once
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/**/*

  seed:
    desc: Upload seed data to local KV.
    run: once
    cmds:
      - npx wrangler kv:bulk put --binding=SHORT_LINKS --local data/seed.json
    sources:
      - data/seed.json

  start:
    desc: Start local development server.
    deps: [dev:setup]
    interactive: true
    cmds:
      - npx wrangler dev
